### ISSUE TITLE
Hedgehog v1.3.3 reports B.1.617.2 for Omicron lineage XBB.1.5.1

### ISSUE THREAD

**Issue by pcparvangada** [cov-lineages/hedgehog#5]
Hi

I'm using hedgehog v1.3.3. with pangolin v1.21. When I input an omicron spike sequence (XBB.1.5.1), the program reports precision=B.1.617.2.

here is the command I used:
hedgehog gisaid_XBB.1.5.1_spike.fas

Here is the taxon ID of the sequence downloaded from GISAID:
CoV-19/USA/TX-PHH-V-142G0190/2023|EPI_ISL_17810955|2023-05-22)

Not sure why the lineage set assignment doesn't include any omicron variants. After reviewing the temporary files, I find that the alignment is accurate. Also, the mutations against reference include the spike constellation listed against XBB.1.5.1 in the set_names.60.csv file.

Am i using the program correctly? 

Thanks

**Comment by aineniamh** [comment]
Hi @pcparvangada, this issue has been flagged to me via email and i'm currently working on a fix. I'm hoping that this issue will be resolved by early next week, but i'm currently trying to get to the root of the issue!

**Comment by aineniamh** [comment]
The latest release should resolve this issue! If any continued problems please flag and I'll try to resolve but I believe it is now fixed!

**Comment by pcparvangada** [comment]
Hi @aineniamh 

Thanks for working on this issue! When I feed the programSpike sequences now, I get precision = B.1.1.529

However, when I pass spike sequences from omicron samples, the results are unchanged from before. I still get precision = B.1.617.2_1. 

Example sequence:
>spike_matching_omicron
atgtttgtttttcttgttttattgccactagtctctagtcagtgtgttaatcttataaccagaactcaatcatacactaattctttcacacgtggtgtttattaccctgacaaagttttcagatcctcagttttacattcaactcaggacttgttcttacctttcttttccaatgttacttggttccatgctatacatgtctctgggaccaatggtactaagaggtttgataaccctgccctaccatttaatgatggtgtttattttgcttccactgagaagtctaacataataagaggctggatttttggtactactttagattcgaagacccagtccctacttattgttaataacgctactaatgttgttattaaagtctgtgaatttcaattttgtaatgatccatttttggatgtttaccaaaaaaacaacaaaagttggatggaaagtgagttcagagtttattctagtgcgaataattgcacttttgaatatgtctctcagccttttcttatggaccttgaaggaaaagagggtaatttcaaaaatcttagggaatttgtgtttaagaatattgatggttattttaaaatatattctaagcacacgcctattaatttagagcgtgatctccctcagggtttttcggctttagaaccattggtagatttgccaataggtattaacatcactaggtttcaaactttacttgctttacatagaagttatttgactcctgttgattcttcttcaggttggacagctggtgctgcagcttattatgtgggttatcttcaacctaggacttttctattaaaatataatgaaaatggaaccattacagatgctgtagactgtgcacttgaccctctctcagaaacaaagtgtacgttgaaatccttcactgtagaaaaaggaatctatcaaacttctaactttagagtccaaccaacagaatctattgttagatttcctaatattacaaacttgtgcccttttcatgaagtttttaacgccaccacatttgcatctgtttatgcttggaacaggaagagaatcagcaactgtgttgctgattattctgtcatatataatttcgcaccatttttcgcttttaagtgttatggagtgtctcctactaaattaaatgatctctgctttactaatgtctatgcagattcatttgtaattagaggtaatgaagtcagccaaatcgctccagggcaaactggaaatattgctgattataattataaattaccagatgattttacaggctgcgttatagcttggaattctaacaagcttgattctaagcctagtggtaattataattacctgtatagattgtttaggaagtctaagctcaaaccttttgagagagatatttcaactgaaatctatcaggccggtaacaaaccttgtaatggtgttgcaggtcctaattgttactctcctttacaatcatatggtttccgacccacttatggtgttggtcaccaaccatacagagtagtagtactttcttttgaacttctacatgcaccagcaactgtttgtggacctaaaaagtctactaatttggttaaaaacaaatgtgtcaatttcaacttcaatggtttaacaggcacaggtgttcttactgagtctaacaaaaagtttctgcctttccaacaatttggcagagacattgctgacactactgatgctgtccgtgatccacagacacttgagattcttgacattacaccatgttcttttggtggtgtcagtgttataacaccaggaacaaatacttctaaccaggttgctgttctttatcagggtgttaactgcacagaagtccctgttgctattcatgcagatcaacttactcctacttggcgtgtttattctacaggttctaatgtttttcaaacacgtgcaggctgtttaataggggctgaatatgtcaacaactcatatgagtgtgacatacccattggtgcaggtatatgcgctagttatcagactcagactaagtctcatcggcgggcacgtagtgtagctagtcaatccatcattgcctacactatgtcacttggtgcagaaaattcagttgcttactctaataactctattgccatacccacaaattttactattagtgttaccacagaaattctaccagtgtctatgaccaagacatcagtagattgtacaatgtacatttgtggtgattcaactgaatgcagcaatcttttgttgcaatatggcagtttttgtacacaattaaaacgtgctttaactggaatagctgttgaacaagacaaaaacacccaagaagtttttgcacaagtcaaacaaatttacaaaacaccaccaattaaatattttggtggttttaatttttcacaaatattaccagatccatcaaaaccaagcaagaggtcatttattgaagatctacttttcaacaaagtgacacttgcagatgctggcttcatcaaacaatatggtgattgccttggtgatattgctgctagagacctcatttgtgcacaaaagtttaacggccttactgttttgccacctttgctcacagatgaaatgattgctcaatacacttctgcactgttagcgggtacaatcacttctggttggacctttggtgcaggtgctgcattacaaataccatttgctatgcaaatggcttataggtttaatggtattggagytacacagaatgttctctatgagaaccaaaaattgattgccaaccaatttaatagtgctattgscaaaattcaagactcactttcttccacagcaagtgcacttggaaaacttcaagatgtggtcaaccataatgcacaagctttaaacacgcttgttaaacaacttagctccaaatttggtgcaatttcaagtgttttaaatgatatcctttcacgtcttgacaaagttgaggctgaagtgcaaattgataggttgatcacaggcagacttcaaagtttgcagacatatgtgactcaacaattaattagagctgcagaaatcagagcttctgctaatcttgctgctactaaaatgtcagagtgtgtacttggacaatcaaaaagagttgatttttgtggaaagggctatcatcttatgtccttccctcagtcagcacctcatggtgtagtcttcttgcatgtgacttatgtccctgcacaagaaaagaacttcacaactgctcctgccatttgtcatgatggaaaagcacactttcctcgtgaaggtgtctttgtttcaaatggcacacactggtttgtaacacaaaggaatttttatgaaccacaaatcattactacagacaacacatttgtgtctggtaactgtgatgttgtaataggaattgtcaacaacacagtttatgatcctttgcaacctgaattagattcattcaaggaggagttagataaatattttaagaatcatacatcaccagatgttgatttaggtgacatctctggcattaatgcttcagttgtaaacattcaaaaagaaattgaccgcctcaatgaggttgccaagaatttaaatgaatctctcatcgatctccaagaacttggaaagtatgagcagtatataaaatggccatggtacatttggctaggttttatagctggcttgattgccatagtaatggtgacaattatgctttgctgtatgaccagttgctgtagttgtctcaagggctgttgttcttgtggatcctgctgcaaatttgatgaagacgactctgagccagtgctcaaaggagtcaaattacattacacataa


Looking at the alignment against wuhan reference (NC_045512), the sequence has mutations characteristic of omicron:
S:S373P, S:K417N, S:N440K, S:G446S, S:S477N, S:T478K, S:E484A, S:Q498R, S:N501Y, S:D614G, S:H655Y, S:N679K, S:P681H, S:N764K, S:D796Y, S:Q954H, S:N969K
